CAPTION = "Eleventh Second"
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
WINDOW_SIZE = WINDOW_WIDTH, WINDOW_HEIGHT
FRAMERATE = 60

CHAMBER_WIDTH = 600
CHAMBER_LEFT = WINDOW_WIDTH//2 - CHAMBER_WIDTH//2
CHAMBER_RIGHT = WINDOW_WIDTH - CHAMBER_LEFT


BLACK = 0, 0, 0

LEFT = 0
RIGHT = 1

BIG = 1
SMALL = 2

BIG_RADIUS = 250
SMALL_RADIUS = 125
RADII = {BIG: BIG_RADIUS,
         SMALL: SMALL_RADIUS}
TOOTH_DEPTH = 35